language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.7
jdk:
  - oraclejdk8

addons:
  firefox: latest
  chrome: stable
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz && tar xf geckodriver-v0.22.0-linux64.tar.gz -C bin
  - export PATH=$PWD/bin:$PATH

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10
  - nvm use 10
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom@9.12.0 source-map-support

script:
  #- sbt -DCI=travis ++$TRAVIS_SCALA_VERSION test:compile JS/test:fastOptJS JS/test:fullOptJS
  - sbt -DCI=travis ++$TRAVIS_SCALA_VERSION test
  # TODO Investigate
  #- sbt -DCI=travis ++$TRAVIS_SCALA_VERSION 'set scalaJSStage in Global := FullOptStage' JS/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
